### PR TITLE
Refactored gradle's build scripts

### PR DESCRIPTION
**Pull request by Vest**
There are many changes, I am doing them, because Gradle is slowly moving toward 9.0, and it plans to throw exceptions for situations, when something is badly designed.

What I am doing, is I am testing different PCGen tasks with --scan option, and trying to optimize the project compilation speed. This PR is draft, so you and me will not forget about it :)

### CODE REVIEW

**Comment by Vest** [comment]
All the changes, I am commenting in commits just in case.

**Comment by karianna** [comment]
@Vest - Thanks, I'll try to get the Java21 branch to build a Windows release as is and then tag that as a commit 'that can build a new release' before I merge the changes from here (but I like what I'm seeing)

**Comment by Vest** [comment]
Thanks for the accepting my idea. I am profiling the build, hoping that with the new API I will be able to reduce the number of redundant tasks that Gradle is executing. 
It is difficult to explain why I am doing this. I am just trying to follow this document: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

**Comment by Vest** [comment]
I am slowly working on this PR. Theoretically, your command line is executed fine on my Win-machine:
```
./gradlew clean build copyToOutput test compileSlowtest datatest pfinttest allReports buildDist
./gradlew prepareRelease slowtest
./gradlew pcgenRelease
```
I will check it once again on Mac.

**Comment by Vest** [comment]
The latest commit breaks :makeNsis, but I will fix it (I hope)

**Comment by Vest** [comment]
155971d is a very important commit. It removes direct dependencies to "package"-kind of tasks for simple scenarios, when we just want to compile our project only.
Previously the :build was very heavy, because we were building the entire project for many platforms. We have to build the project for the current platform only. It isn't a distribution for all supported platforms (I guess)

**Comment by Vest** [comment]
This is a draft version still, but I hope it will be much better to what we have right now. It is far from the end :(

**Comment by Vest** [comment]
@karianna I hope, you are doing well, and you haven't forgot about this PR 😇

**Comment by Vest** [comment]
Should I update this PR with changes from the master? E.g. resolve the conflicts and update dependencies.

**Comment by karianna** [comment]
Yes still alive - just travelling for the next couple of weeks - will try to wrap this up this weekend!

**Pull request merged**
