### PR TITLE
Formatted output for downloadJRE and downloadJavaFXModules a little

### PR DESCRIPTION
**Pull request by Vest**
In general, I have refactored code a little bit and removed few warnings detected by IDEA.

### CODE REVIEW

**Comment by Vest** [comment]
You can test the output via `clear && gradle downloadJavaFXModules`

**Comment by karianna** [comment]
@Vest The Linux Aarch 64 jmods download seemed to work (for 21.0.1 anyhow), so I think we can retian that platofrm?

**Comment by Vest** [comment]
@karianna I have added a filter where I select arm together with Mac only. I can remove it. Should I?
but I haven’t changed your version 21.0.1. Let’s leave it as it is… for a while. I don’t want to stick to 21.0.1 JavaFX for a long time.

**Comment by karianna** [comment]
Yeah I think remove that special filter and instead I'll upgrade 'all' mods downloads to 21.0.2 but special case the Linux aarch 64 mods download to be 21.0.1.  Rest of the PR looks great!

**Comment by Vest** [comment]
@karianna  done.
I have build the project only, but I didn't run all the tests.

**Comment by Vest** [comment]
@karianna I couldn't resist myself, so I pushed one more commit. It will resolve https://github.com/PCGen/pcgen/pull/7073

**Review by karianna — APPROVED** [review]

**Pull request merged**
